# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-role
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["list", "get", "watch"]

---
# Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-pods
subjects:
- kind: ServiceAccount
  name: pod-list
  namespace: default
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole
  name: pod-role
  apiGroup: rbac.authorization.k8s.io

  