apiVersion: v1
kind: Pod
metadata:
  name: two-pod
spec:
  containers:
  - name: pod1
    image: busybox
    command: ['sh', '-c', 'echo "pod one data" >> /root/file.txt']
    volumeMounts:
    - mountPath: /root
      name: emptydir
  - name: pod2
    image: busybox
    command:
        - cat
        - /root/file.txt
    volumeMounts:
    - mountPath: /root
      name: emptydir
  volumes:
  - name: emptydir
    emptyDir: {}
